### ISSUE TITLE
Port generation

### ISSUE THREAD

**Issue by OSMaxwell** [demirsenturk/intel_plug-tool#3]
![image](https://user-images.githubusercontent.com/48519746/80481273-6a2ed880-8952-11ea-9bec-2a8bd4e247b4.png)

After discovering the CDP, the program should generate a new port. 
**The new port = the old port (Wall plug) +1** 
In the picture above, the Wall plug number should be 688, instread is just reads the first plog in the list.

**Comment by demirsenturk** [comment]
40. Commit includes a solution about the issue.
